/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Yirz
 */
public class GUI extends javax.swing.JFrame {
    private ManejadorMysql mysql,remote1,remote2,remote3;
    private ResultSet rs;
    private String Atributo;
    private String RelacionHorizontal;
    private String RelacionVertical;
    private String Operador;
    ArrayList<PredicadoSimple> predicados;
    ArrayList <Pre_Minitermino> miniterminos;
    ArrayList<JCheckBox> checkBox;
    ArrayList<String> expresiones; //---
    ArrayList<String> expre; //---
    String prediSim;
    /**
     * Creates new form GUI
     */
    public GUI() {
        mysql=new ManejadorMysql("jdbc:mysql://127.0.0.1:3306/galardonado_galardonados","luisca","root",0);
        remote1=new ManejadorMysql("jdbc:mysql://127.0.0.1:3306/s1","luisca","root",1);
        remote2=new ManejadorMysql("jdbc:mysql://127.0.0.1:3306/s2","luisca","root",2);
        remote3=new ManejadorMysql("jdbc:mysql://127.0.0.1:3306/s3","luisca","root",3);
        predicados=new ArrayList();
        miniterminos = new ArrayList();         //Se agrego un array para miniterminos!----------------------------
        checkBox=new ArrayList();
        expresiones=new ArrayList();//---
        expre= new ArrayList();//---
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Genera_Minit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Miniterms_jScroll = new javax.swing.JScrollPane();
        jTableMiniTerms = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Sitio = new javax.swing.JComboBox<ManejadorMysql>();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jComboBox5 = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sitio1 = new javax.swing.JComboBox<ManejadorMysql>();
        EnviarExpresion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Definir Condiciones de Fragmentación"));

        jLabel1.setText("Leer Relacion");

        try{
            rs=mysql.QueryRead("SHOW TABLES");
            while(rs.next()){
                jComboBox1.addItem(rs.getString("Tables_in_galardonado_galardonados"));
                jComboBox4.addItem(rs.getString("Tables_in_galardonado_galardonados"));
            }
            String s=jComboBox1.getItemAt(0);
            this.CreateTable(s,jScrollPane1);
            this.CreateTable(s,jScrollPane3);
            this.AddItems(s);
            this.CreateCheckBox(s);
            RelacionHorizontal=s;
            RelacionVertical=s;
            Atributo=jComboBox2.getItemAt(0);
        }
        catch(SQLException ex){
            ex.printStackTrace();
        }
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Fragmentos Miniterminos"));

        jScrollPane2.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Predicado Simple", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(290);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        Genera_Minit.setText("Generar miniterminos");
        Genera_Minit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genera_MinitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 409, Short.MAX_VALUE)
                        .addComponent(Genera_Minit)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Genera_Minit)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Definir Predicados simples"));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">", "<>", "<=", ">=" }));
        Operador=jComboBox3.getItemAt(0);
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Atributo");

        jLabel3.setText("Operador");

        jLabel4.setText("Valor");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 126, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Colocar Fragmentos Miniterminos"));

        Miniterms_jScroll.setBorder(null);

        jTableMiniTerms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Minitermino", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMiniTerms.setEnabled(true);
        jTableMiniTerms.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        Miniterms_jScroll.setViewportView(jTableMiniTerms);
        if (jTableMiniTerms.getColumnModel().getColumnCount() > 0) {
            jTableMiniTerms.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        jLabel7.setText("Sitio:");

        Sitio.addItem(remote1);
        Sitio.addItem(remote2);
        Sitio.addItem(remote3);
        Sitio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SitioItemStateChanged(evt);
            }
        });
        Sitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SitioActionPerformed(evt);
            }
        });

        jButton4.setText("Examinar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviaFragmento(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Miniterms_jScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sitio, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Miniterms_jScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Sitio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane3.addTab("Fragmentación Horizontal", jPanel1);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Definir Dominio del Fragmento"));

        jLabel5.setText("Cargar Relación");

        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });

        jScrollPane3.setBorder(null);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Expresiones Algebraicas"));

        jScrollPane4.setBorder(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Expresion", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(true);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar Atributos"));

        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });

        jLabel6.setText("Atributo");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(82, 82, 82))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Colocación de Fragmentos"));

        jLabel8.setText("Sitio:");

        Sitio1.addItem(remote1);
        Sitio1.addItem(remote2);
        Sitio1.addItem(remote3);
        Sitio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Sitio1ItemStateChanged(evt);
            }
        });
        Sitio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sitio1ActionPerformed(evt);
            }
        });

        EnviarExpresion.setText("Examinar");
        EnviarExpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarExpresionEnviaFragmento(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sitio1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(EnviarExpresion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Sitio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnviarExpresion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Fagmentación Vertical", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        if( evt.getStateChange() == ItemEvent.SELECTED ){
            Object item= evt.getItem();
            Atributo=item.toString();
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        if( evt.getStateChange() == ItemEvent.SELECTED ){
            Object item= evt.getItem();
            Operador=item.toString();
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jTextField1.getText().equals("")){
       
       
       }
       else{
           PredicadoSimple ps=new PredicadoSimple(Atributo,Operador,jTextField1.getText(),RelacionHorizontal);
           try {
               this.AddPredicado(ps);
           } catch (SQLException ex) {
               Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       }
    }//GEN-LAST:event_jButton1ActionPerformed
                                      
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if( evt.getStateChange() == ItemEvent.SELECTED ){
            Object item= evt.getItem();
            RelacionHorizontal=item.toString();
            try {
                
                this.CreateTable(item.toString(),jScrollPane1);
                this.AddItems(item.toString());
                this.ClearTable(jTable1,jScrollPane1);
                this.ClearTable(jTableMiniTerms,Miniterms_jScroll);
                predicados.clear();
                miniterminos.clear();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        expresiones.clear();
        for(int i=0; i<checkBox.size(); i++){
            if(checkBox.get(i).isSelected()){
                expresiones.add(checkBox.get(i).getText());
            }
        }
        Expresion exp=new Expresion(expresiones,RelacionVertical);
        try{
            this.AddExpresion(exp);
        } catch(SQLException ex){
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        if( evt.getStateChange() == ItemEvent.SELECTED ){
            Object item= evt.getItem();
            RelacionVertical=item.toString();
            try {
                this.CreateTable(item.toString(),jScrollPane3);
                this.CreateCheckBox(item.toString());
                this.ClearTable(jTable2,jScrollPane4);
                expre.clear();
                expresiones.clear();
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void SitioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SitioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SitioItemStateChanged

    private void EnviaFragmento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviaFragmento
        ArrayList<Pre_Minitermino> miniterminoAux=this.getMiniterminos();
        if(miniterminoAux.size()==0){
            JOptionPane.showMessageDialog(new Frame(),"Selecciones por lo menos un minitermino");
        }
        else{
            Sender sender=new Sender();
            ManejadorMysql aux=(ManejadorMysql)Sitio.getSelectedItem();
            for(int i=0;i<miniterminoAux.size();i++){
                try {
                    sender.SendQueryHorizontal(miniterminoAux.get(i).getPredicado1().getRelacion(),
                            mysql.QueryRead(this.QueryMinitermino(miniterminoAux.get(i))),
                            mysql.getConnection(),aux.getConnection());
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                miniterminos.remove(miniterminoAux.get(i));
            }
            this.ClearTable(this.jTableMiniTerms,this.Miniterms_jScroll);
            DefaultTableModel model=(DefaultTableModel) jTableMiniTerms.getModel();
            for(int i=0;i<miniterminos.size();i++){
                String id=""+model.getRowCount();
                Object []auxObj={id,miniterminos.get(i).toString(),false};
                model.addRow(auxObj);
            }
            jTableMiniTerms.setModel(model);
            Miniterms_jScroll.updateUI();
        }
    }//GEN-LAST:event_EnviaFragmento

    private void AddExpresion(Expresion exp) throws SQLException{
        String ex = exp.toString();
        int n;
        //System.out.println("Expresion: "+exp.toString());
        n = ValidarExp(exp);
        //System.out.println("Valor n = "+ n);
        if(n == 0){
            JOptionPane.showMessageDialog(new Frame(),"Esta expresión ya se ingreso");
        }
        else{
        expre.add(ex);
        /*for(int i=0; i<expre.size();i++){
            System.out.println("Expresion "+i+" : "+expre.get(i).toString());
        }*/
        DefaultTableModel mode2 = (DefaultTableModel) jTable2.getModel();
        int id = mode2.getRowCount();
        Object []aux = {id,ex,false};
        mode2.addRow(aux);
        jTable2.setModel(mode2);
        jScrollPane4.updateUI();
        System.out.println("Expresion agregada con exito"); 
        }
        //expresiones.clear();
    }
    private int ValidarExp(Expresion exp) throws SQLException{
        //System.out.println("Tamaño: " + expre.size());
        String ex = exp.toString();
        if(expre.isEmpty()){
            return 1;
        }// Podría sobrar esta parte
        for(int i=0; i<expre.size(); i++){
            //System.out.println(expre.get(i));
            if(ex.equals(expre.get(i))){
                return 0;
            }
        }
        return 1;
    }
    private void Genera_MinitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genera_MinitActionPerformed
        //-------------------------------Esto lo hizo Emm --------------------------------------------------------
        ArrayList<PredicadoSimple> predicadoAux=this.getPredicados();
        
        if(predicadoAux.size()!=2){
            JOptionPane.showMessageDialog(new Frame(),"Selecciones solo dos predicados simple para generar Miniterminos");
        }
        else{
            PredicadoSimple p1=predicadoAux.get(0),p2=predicadoAux.get(1);
            for(int i=0;i<predicadoAux.size();i++){
                for(int j=0;j<predicadoAux.size();j++){
                    try {
                        this.AddMinitermino(new Pre_Minitermino(p1,p2));
                    } catch (SQLException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    p2=p2.NotPredicado();
                }
                p1=p1.NotPredicado();
                p2=p2.NotPredicado();
            }
        }
       
    }//GEN-LAST:event_Genera_MinitActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void SitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SitioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SitioActionPerformed

    private void Sitio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Sitio1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Sitio1ItemStateChanged

    private void Sitio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sitio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sitio1ActionPerformed

    private void EnviarExpresionEnviaFragmento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarExpresionEnviaFragmento
        // TODO add your handling code here:
        ArrayList <String> Expresion_aux = this.getExpresiones();
        if(Expresion_aux.isEmpty()){
            JOptionPane.showMessageDialog(new Frame(),"Selecciona por lo menos una expresion");
        }
        else{
            Sender sender=new Sender();
            ManejadorMysql aux=(ManejadorMysql)Sitio1.getSelectedItem();
            for(int i=0;i<Expresion_aux.size();i++){
                
                try { 
                    sender.SendQueryVertical(RelacionVertical,
                            mysql.QueryRead(this.QueryExpresion(Expresion_aux.get(i),RelacionVertical)),
                            mysql.getConnection(),aux.getConnection());
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                expre.remove(Expresion_aux.get(i));
            }
            this.ClearTable(this.jTable2,this.jScrollPane4);
            DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
            for(int i=0;i<expre.size();i++){
                String id=""+model.getRowCount();
                Object []auxObj={id,expre.get(i).toString(),false};
                model.addRow(auxObj);
            }
            jTable2.setModel(model);
            jScrollPane4.updateUI();
        }
    }//GEN-LAST:event_EnviarExpresionEnviaFragmento
    private void ClearTable(JTable table,JScrollPane jp){
        DefaultTableModel model=(DefaultTableModel) table.getModel();
        if(model.getRowCount()!=0){
            while(model.getRowCount()>0){
                model.removeRow(0);
            }
            table.setModel(model);
            jp.updateUI();
        }
    }
    
    private void CreateTable(String item,JScrollPane panel) throws SQLException{
        DefaultTableModel model = new DefaultTableModel();
        JTable table;
        rs=mysql.QueryRead("desc "+item);
        int cont=0;
        while(rs.next()){
            String []aux={rs.getString("Field")};
            model.addColumn("Atributo "+cont,aux);
            cont++;
        }
        table=new JTable(model);
        table.setEnabled(false);
        panel.setViewportView(table);
        panel.updateUI();
    }
    private void AddItems(String item) throws SQLException{
        rs=mysql.QueryRead("desc "+item);
        if(jComboBox2.getItemCount()!=0){
            jComboBox2.removeAllItems();
        }
        while(rs.next()){
            jComboBox2.addItem(rs.getString("Field"));
        }
        Atributo=jComboBox2.getItemAt(0);
    }
    private void AddPredicado(PredicadoSimple ps) throws SQLException{   
        //Nuevo, Emm hizo esto: -----------------------------------------------------------------------------
        String p = ps.toString();
        String query_predicado;
        //int indice_Antes_Relacion = p.indexOf("(");
        //prediSim = p.substring(0, indice_Antes_Relacion);
        String tipo_dato="Select  data_type from information_schema.columns WHERE TABLE_NAME='"+ps.getRelacion()+"' and column_name='"+ps.getAtributo()+"'";
        //System.out.println(tipo_dato);
        ResultSet aux1=mysql.QueryRead(tipo_dato);
        aux1.next();
        if(aux1.getString("data_type").equals("varchar")){
            query_predicado = "Select * from "+ ps.getRelacion()+" where "+ps.getAtributo()+""+ps.getOperador()+"'"+ps.getValor()+ "'";
        }
        else{
            query_predicado = "Select * from "+ ps.getRelacion()+" where "+ps.getAtributo()+""+ps.getOperador()+""+ps.getValor()+ "";
        }
        ResultSet aux_pred=mysql.QueryRead(query_predicado);
        
//        aux_pred.next();
//        String imprimir = aux_pred.getString(1);
//            System.out.println(ps.getRelacion());
//            System.out.println(prediSim);
//            System.out.println(query_predicado);
//        System.out.println(imprimir);        
        if(!aux_pred.next()){           //Aqui probamos si el predicado genera resultados (no es nulo)
            JOptionPane.showMessageDialog(new Frame(),"El predicado no es valido, es un conjunto vacio");
        }

        else {
            predicados.add(ps);
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            int id=model.getRowCount();
            Object []aux={id,ps,false};
            model.addRow(aux);
            jTable1.setModel(model);
            jScrollPane2.updateUI();
            System.out.println("Predicado agregado con exito");
        }
        
    }
    private String QueryMinitermino(Pre_Minitermino mt) throws SQLException{
        PredicadoSimple p1,p2;
        p1=mt.getPredicado1();
        p2=mt.getPredicado2();
        String tipo_dato_p1="Select  data_type from information_schema.columns WHERE TABLE_NAME='"+p1.getRelacion()+"' and column_name='"+p1.getAtributo()+"'";
        String tipo_dato_p2="Select  data_type from information_schema.columns WHERE TABLE_NAME='"+p2.getRelacion()+"' and column_name='"+p2.getAtributo()+"'"; 
        ResultSet dato_p1=mysql.QueryRead(tipo_dato_p1);
        ResultSet dato_p2=mysql.QueryRead(tipo_dato_p2);
        dato_p1.next();
        dato_p2.next();
        String pre1_string="";
        String pre2_string="";
        if(dato_p1.getString("data_type").equals("varchar")){
            pre1_string="'"+p1.getValor()+"'";
        }
        else{
            pre1_string=p1.getValor();
        }
        if(dato_p2.getString("data_type").equals("varchar")){
            pre2_string="'"+p2.getValor()+"'";
        }
        else{
            pre2_string=p2.getValor();
        }
        String query_miter = "Select * from "+ p1.getRelacion()+" where "+p1.getAtributo()+""+p1.getOperador()+""+pre1_string+" and "+p2.getAtributo()+""+p2.getOperador()+""+pre2_string+"";
        System.out.println(query_miter);
        return query_miter;                
    }
    private String QueryExpresion(String exp,String Relacion) throws SQLException{
        String[] partes = exp.split("-");
        System.out.println(partes[0]);
        System.out.println(partes[1]);
        String frag_exp="Select "+partes[0]+" from "+Relacion;
        System.out.println(frag_exp);
        return frag_exp;                
    }
    private void AddMinitermino(Pre_Minitermino mt) throws SQLException{
         //Nuevo, Emm hizo esto: --------------------------------------------------------------------------------------
        String query_miter=this.QueryMinitermino(mt);
        System.out.println(query_miter);
        ResultSet aux_mt=mysql.QueryRead(query_miter);
        
//        aux_pred.next();
//        String imprimir = aux_pred.getString(1);
//            System.out.println(ps.getRelacion());
//            System.out.println(query_predicado);
//        System.out.println(imprimir);        
        
        if(!aux_mt.next()){           //Aqui probamos si el miniter. genera resultados (no es nulo)
            System.out.println("El minitermino "+ mt +  " no es valido");
        }

        else {
            miniterminos.add(mt);
            DefaultTableModel model=(DefaultTableModel) jTableMiniTerms.getModel();
            String id=""+model.getRowCount();
            Object []aux={id,mt.toString(),false};
            model.addRow(aux);
            jTableMiniTerms.setModel(model);
            Miniterms_jScroll.updateUI();
            System.out.println("Minitermino "+ mt +  " agregado con exito");
        }
        
    }
    private ArrayList<PredicadoSimple> getPredicados(){
        ArrayList<PredicadoSimple> aux =new ArrayList();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int row=model.getRowCount();
        for(int i=0;i<row;i++){
            if((boolean)model.getValueAt(i,2)){
                aux.add(predicados.get(i));
            }
        }
        return aux;
    }
    private ArrayList<Pre_Minitermino> getMiniterminos(){
        ArrayList<Pre_Minitermino> aux =new ArrayList();
        DefaultTableModel model=(DefaultTableModel)jTableMiniTerms.getModel();
        int row=model.getRowCount();
        for(int i=0;i<row;i++){
            if((boolean)model.getValueAt(i,2)){
                aux.add(miniterminos.get(i));
            }
        }
        return aux;
    }
    private ArrayList<String> getExpresiones(){
        ArrayList<String> aux =new ArrayList();
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        int row=model.getRowCount();
        for(int i=0;i<row;i++){
            if((boolean)model.getValueAt(i,2)){
                aux.add(expre.get(i));
            }
        }
        return aux;
    }
    private void CreateCheckBox(String item) throws SQLException{
        String query="Select  count(*) as Atr from information_schema.columns where table_name='"+item+"'";
        ResultSet aux=mysql.QueryRead(query);
        if(jPanel11.getComponentCount()!=0 && checkBox.size()!=0){
            jPanel11.removeAll();
            checkBox.clear();
        }
        rs=mysql.QueryRead("desc "+item);
        aux.next();
        jPanel11.setLayout(new GridLayout(5,2));
        while(rs.next()){
            checkBox.add(new JCheckBox(rs.getString("Field")));
            if(rs.isFirst()){
                checkBox.get(checkBox.size()-1).setSelected(true);
                checkBox.get(checkBox.size()-1).setEnabled(false);
            }
            jPanel11.add(checkBox.get(checkBox.size()-1));
        }
        jPanel11.revalidate();
        jPanel11.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarExpresion;
    private javax.swing.JButton Genera_Minit;
    private javax.swing.JScrollPane Miniterms_jScroll;
    private javax.swing.JComboBox<ManejadorMysql> Sitio;
    private javax.swing.JComboBox<ManejadorMysql> Sitio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableMiniTerms;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
